###
# This file configures the SAP Cloud SDK Continuous Delivery pipeline of your project.
# For a reference of the configuration concept and available options, please have a look into its documentation.
#
# The documentation for the most recent pipeline version can always be found at:
#    https://github.com/SAP/cloud-s4-sdk-pipeline/blob/master/configuration.md
# If you are using a fixed version of the pipeline, please make sure to view the corresponding version from the tag
# list of GitHub (e.g. "v15" when you configured pipelineVersion = "v15" in the Jenkinsfile).
#
# For general information on how to get started with Continuous Delivery, visit:
#    https://blogs.sap.com/2017/09/20/continuous-integration-and-delivery
#
# We aim to keep the pipeline configuration as stable as possible. However, major changes might also imply breaking
# changes in the configuration. Before doing an update, please check the the release notes of all intermediate releases
# and adapt this file if necessary.
#
# This is a YAML-file. YAML is a indentation-sensitive file format. Please make sure to properly indent changes to it.
###



### General project setup
general:
  unsafeMode: false
  projectName: 'cloud-cap-s4ems-bp'
  productiveBranch: 'master'

### Step-specific configuration
steps:
  mavenExecute:
    dockerImage: devxci/mbtci:1.0.14
  artifactPrepareVersion:
    buildTool: 'mta'
    npmExecute:
    dockerImage: 's4sdk/docker-node-browsers:v15'
  cloudFoundryDeploy:
    dockerImage: 'ppiper/cf-cli'
    deployType: 'standard'
    mtaDeployParameters: '-f --version-rule ALL'
  sapNexusStage:
    stagingProfile: 'integration'
    repositoryFormat: 'npm'
  sapNexusUploadArtifacts:
    packaging: 'mtar'
    buildDescriptorFile: 'mta.yaml'
    uploadFile: 'BusinessPartnerValidation_1.0.0.mtar'
    artifactType: 'mta'
  mtaBuild:
    mtaBuildTool: "cloudMbt"


### Stage-specific configuration
stages:
  npmAudit:
    auditedAdvisories:
    # high
      - 550   
      - 593
      - 1184
      - 755
      - 1065 
      - 1164 
      - 1316 
      - 1324 
      - 1325 
    # moderate
      - 535
      - 1300 
      
#  backendIntegrationTests:
 #   createHdiContainer: true
  #  cloudFoundry:
   #   org: 'referenceappscf'
    #  space: 'SF_CAP'
     # apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      #credentialsId: 'cfdeployuser'

  lint:
    ui5BestPractices:
      failThreshold:
        error: 100
        warning: 500
        info: 1000
        
  #endToEndTests:
    #cfTargets:
     # - org: 'referenceappscf'
      #  space: 'SF_CAP'
       # apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
        #credentialsId: 'cfdeployuser'
    #appUrls:
     # - url: 'https://referenceappscf-sf-cap-media-server-srv.cfapps.eu10.hana.ondemand.com'
      #  credentialId: 'cfdeployuser'

#  integrationTests:
#    credentials:
#      - alias: 'mySystemAlias'
#        credentialId: 'mySystemCredentialsId'

productionDeployment:
   cfTargets:
     - org: 'TTC_FIORI_24sihpa2t7u14zcd'
       space: 'dev'
       apiEndpoint: 'https://api.cf.sap.hana.ondemand.com'
       appName: 'myAppName'
       manifest: 'manifest.yml'
       credentialsId: 'global'
